language: node_js
node_js:
  - stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run test:e2e

after_success:
  - npm run build production

deploy:
  local_dir: ./dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN

branches:
  only:
    - master

notifications:
  email:
    - kingispeak@gmail.com
  on_failure: always

env:
  global:
    - GH_REF: github.com/kingispeak//tw-covid-19.git
